### ISSUE TITLE
J2J measures contain fields not in CSV

### ISSUE THREAD

**Issue by srt1** [labordynamicsinstitute/qwi_schemas#40] opened 2017-01-10 19:24 UTC
Version 4.1.0 schema contains measures not in the CSV, intended for the web application. These need to be split up or flagged differently (the J2J and J2JFullQ measures are not in the csv)

https://lehd.ces.census.gov/data/schema/V4.1.0/lehd_public_use_schema.html#_job_to_job_flow_origin_destination_j2jod

Is it possible that this has happened to other measure sets?

**Comment by heathhayward** [comment] 2017-03-06 18:24
Here are the 4 files zipped up (csv's aren't supported here). Let me know if you have any questions.

[J2J.zip](https://github.com/labordynamicsinstitute/qwi_schemas/files/822071/J2J.zip)

**Comment by larsvilhuber** [comment] 2017-03-07 01:08
@srt1 @heathhayward I am going to need to split this into two: 

- removing the measures not provided on the CSV (in scope for 4.1.1, also correction to 4.1.0)
- Creation of an ADDITIONAL file for the apps (do you need this for 4.1.1 which is PRODUCTION or does this relate to a potential changing aspect of a beta APP for beta DATA? in which case it is 4.2a-draft)

I am REMOVING the additional columns from the variables_j2j*csv files, which are (a) related to an app? (b) not acceptable in 4.1.1 (if anything 4.2a-draft). We managed to get the variables_{qwi,j2j} onto the same format, I'm not breaking that again.

**Comment by heathhayward** [comment] 2017-03-07 13:41
I've told Excensus to use a hard copy of the variables_j2japp.csv file that includes the Concept column for the time being.  So feel free to drop that column for the official schema until you are ready.  But J2J Explorer does need that field, so if we want the application to use our official schema we will need to add it in eventually.

**Comment by larsvilhuber** [comment] 2017-03-07 13:44
I only said it was not appropriate for the "production" schema 4.1. I totally agree that the "Concept field" should be there, ... in 4.2a-draft for starters, which once published, Excensus can use.

We are back to navigating the evolving requirements of a beta app using beta data referencing production or draft specs. draft specs can evolve rapidly, production specs by design MUST not.

When we add the Concept field, we will add it to ALL variables fields. No earlier than 4.2

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
U.S. Census Bureau - CES - LEHD

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://www.vilhuber.com/lars/

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346


________________________________________

**Comment by larsvilhuber** [comment] 2017-03-07 14:09
this is solved in V4.1.0, moving this to V4.2a-draft.

**Comment by larsvilhuber** [comment] 2017-04-03 15:16
@srt1 @heathhayward : please have a look at the lehd_j2japp_schema.html file that I created. I know that the variables_j2japp.csv will change again, but I assumed you might want a more focused document to describe it (rather than integrating it into the global specs). (you will need to download it to view it)

**Comment by heathhayward** [comment] 2017-04-03 16:07
If this document is created only for J2J Explorer, do we need to mention the QWI data?  and should the J2JR data be referenced (I only see QWI, J2JOD and J2J mentioned in section 5.2)?  instead of saying "J2Japp" can we say "J2J Explorer" (in "Purpose")?

**Comment by larsvilhuber** [comment] 2017-04-03 16:50
Goal is to only document the data exported from J2J Explorer.

Download the relevant *asciidoc file, edit it to suit your needs, and upload to the issue. (with .txt extension)

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/

Assistant: ldi@cornell.edu | +1.607-255-2744

GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346


________________________________________

**Comment by heathhayward** [comment] 2017-04-03 18:55
What are you referring to a the bottom of "Generic Structure" where you say: "Note: J2J Explorer provides a COMPLETE THIS."? 
[lehd_j2japp_schema.txt](https://github.com/labordynamicsinstitute/qwi_schemas/files/891057/lehd_j2japp_schema.txt)

**Comment by larsvilhuber** [comment] 2017-04-03 19:37
Needs text. See kind of text in other templates.



--
Sent from my mobile device


-------- Original message --------

**Comment by heathhayward** [comment] 2017-04-03 19:48
how does this look?

[lehd_j2japp_schema.txt](https://github.com/labordynamicsinstitute/qwi_schemas/files/891196/lehd_j2japp_schema.txt)

**Comment by heathhayward** [comment] 2017-04-03 20:51
looks good.

**Closed** 2017-05-03 20:07 UTC
